version: '3.8'

services:
  nuxt:
    build: .
    container_name: nuxt_app
    ports:
      - "3000:3000"   # временно для проверки
    # expose убираем, используем ports

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "3001:3000"     # на другой порт, чтобы не конфликтовать
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nuxt