events {}

http {
  server {
    listen 443;
    server_name mazloevtest.dev.vbtec.ru;

    location / {
      proxy_pass http://nuxt_app:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}